// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgtCgk3cZ2uV77YU5E__f2DxIPUcxml44',
    appId: '1:920214549430:web:e325154668034660ef0717',
    messagingSenderId: '920214549430',
    projectId: 'moohigo-fb6ea',
    authDomain: 'moohigo-fb6ea.firebaseapp.com',
    storageBucket: 'moohigo-fb6ea.firebasestorage.app',
    measurementId: 'G-100T2G07QT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTN7k_XW6NNBgCTw9LKf2tjEZfEmOY9Ks',
    appId: '1:920214549430:android:c3b4ee35be1d8b57ef0717',
    messagingSenderId: '920214549430',
    projectId: 'moohigo-fb6ea',
    storageBucket: 'moohigo-fb6ea.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDoM6vetYi_X1uqVLsH0ZiuJMMUkcIBmMc',
    appId: '1:920214549430:ios:77a020c6151a7fcdef0717',
    messagingSenderId: '920214549430',
    projectId: 'moohigo-fb6ea',
    storageBucket: 'moohigo-fb6ea.firebasestorage.app',
    iosBundleId: 'com.example.moohigo',
  );
}
